const START_CHAT = 'START_CHAT';
const UPDATE_OLD_CHAT = 'UPDATE_OLD_CHAT';
const APPEND_NEW_CHAT = 'APPEND_NEW_CHAT';
const END_CHAT = 'END_CHAT';
 
export { START_CHAT, UPDATE_OLD_CHAT, APPEND_NEW_CHAT, END_CHAT };