const START_CHAT = 'START_CHAT';
const UPDATE_OLD_CHAT = 'UPDATE_OLD_CHAT';
const APPEND_NEW_CHAT = 'APPEND_NEW_CHAT';
const HE_IS_ONLINE = 'HE_IS_ONLINE';
const HE_IS_OFFLINE = 'HE_IS_OFFLINE';
const END_CHAT = 'END_CHAT';
 
export { START_CHAT, UPDATE_OLD_CHAT, APPEND_NEW_CHAT, HE_IS_ONLINE, HE_IS_OFFLINE, END_CHAT };